/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package googol99;

import java.io.FileInputStream;
import java.io.IOException;
import java.util.Scanner;

/**
 *
 * @author USER
 */
public class GOOGOL99GUI extends javax.swing.JFrame {

    /**
     * Creates new form GOOGOL99GUI
     */
    public GOOGOL99GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1600, 1200));
        setMinimumSize(new java.awt.Dimension(807, 540));
        setPreferredSize(new java.awt.Dimension(807, 540));

        jPanel1.setLayout(null);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(140, 170, 510, 40);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(130, 290, 520, 210);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(320, 230, 130, 40);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GOOGOL..");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 60, 380, 110);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\hahahahahahaha.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 810, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String txt = "";
        try{
        Scanner inputFrmFile = new Scanner(new FileInputStream("C:\\Users\\USER\\Desktop\\Websites2.txt"));
         Scanner inputFrmFile1 = new Scanner(new FileInputStream("C:\\Users\\USER\\Desktop\\Websites2.txt"));
Scanner inputFrmFile2 = new Scanner(new FileInputStream("C:\\Users\\USER\\Desktop\\Tags2.txt"));
Scanner inputFrmUser = new Scanner(System.in);
int counter1=0;
int counter2=0;
        while(inputFrmFile.hasNextLine())//this while loop is for counting how many rows (0-500)
        {
           String a = inputFrmFile.nextLine();
           counter1++;   
        }
String[] websites = new String[counter1];//innitialize the array
String[] tags     = new String[counter1];
int i=0;//initialize for websites and tags
String userInput;

while(inputFrmFile2.hasNextLine()){ //to split the arrays by comas
        String sites = inputFrmFile1.nextLine();
        String tagging = inputFrmFile2.nextLine();
        websites[i]=sites;
        tags[i]=tagging;
        i++;
}
        System.out.print("search Googol: ");
        //userInput = inputFrmUser.nextLine();
        
        //---------------------------input----------------
        userInput = jTextField1.getText();
        
        //--------------------------------------
        
        
        if(userInput.equalsIgnoreCase("googol games"))
        {
            frontpagegame zz = new frontpagegame();
            zz.setVisible(true);
            
        }else if(userInput.equalsIgnoreCase("calculator")){
            latestcalculatorgui xx = new latestcalculatorgui();
            xx.setVisible(true);
        }
        else if(userInput.contains("+")||userInput.contains("*")||userInput.contains("-")||userInput.contains("/")){
            calculator xx = new calculator();
            xx.setVisible(true);
            xx.seteq(userInput);
        }else if(userInput.equalsIgnoreCase("graphing calculator")){
            graphplot cc = new graphplot();
            cc.setVisible(true);
        }else if(userInput.equalsIgnoreCase("roll dice")){
            rolldice vv = new rolldice();
            vv.setVisible(true);
        }else if(userInput.equalsIgnoreCase("convert temperature")||userInput.equalsIgnoreCase("temperature converter")){
            temperatureconverter bb = new temperatureconverter();
            bb.setVisible(true);
        }else if(userInput.contains("currency")||userInput.contains("exchange")){
            
             CurrencyExchange NN = new CurrencyExchange();
             String meg = NN.moneyExchangeList();
             txt+=meg;
        }else if(userInput.contains("convert")){
                  
                  CurrencyExchange MM = new CurrencyExchange();
                  txt = MM.changeMoney(userInput);
                  //System.out.println("megat");
                  //jTextArea1.setText(hensem);
                  //jTextArea1.setText("megat hensem");
                  
                 // String mag = MM.changeMoney(userInput);
                  
        }else if(userInput.contains("megat"))
        {
            txt += "Megat seorang yang sungguh hensem sehingga ramai yang pengsan melihatnya";
        }
        else if(userInput.contains("crush"))
        {
            txt += "Sorry, You dont have any crush " +"\uD83D\uDC94";
        }
        else 
        {
        for (int j = 0; j < counter1; j++) {
            if (tags[j].contains(userInput)) {
                System.out.println(websites[j]);
                txt+=websites[j];
                txt += "\n";
                counter2++;
            }else if(websites[j].contains(userInput)){
                    System.out.println(websites[j]);
                    txt+=websites[j];
                    txt += "\n";
                    counter2++;
             }
 
            }
    if(counter2==0){
                System.out.println("");
                txt +="\n";
                System.out.print("Your search - "+userInput+" - "+ "did not match any documents."); 
                txt += "Your search - "+userInput+" - "+ "did not match any documents.\n";
                System.out.println("");
                System.out.println("Suggestions:");
                txt += "Suggestions:\n";
                System.out.println("");
                System.out.println("-Make sure that all words are spelled correctly.\n");
                txt += "-Make sure that all words are spelled correctly.\n";
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
        
        catch(IOException e){
        System.out.println("megat hensem");
}
        
        jTextArea1.setText(txt);
}
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GOOGOL99GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GOOGOL99GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GOOGOL99GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GOOGOL99GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GOOGOL99GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
