/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package googol99;

public class graphplot extends javax.swing.JFrame {

    /**
     * Creates new form graphplot
     */
    public graphplot() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        front = new javax.swing.JPanel();
        linear = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        power = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        quad = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        exp = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        log = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        sine = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        cosine = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout frontLayout = new javax.swing.GroupLayout(front);
        front.setLayout(frontLayout);
        frontLayout.setHorizontalGroup(
            frontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
        frontLayout.setVerticalGroup(
            frontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );

        jLayeredPane1.add(front, "card2");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Y = mX + b");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ENTER M : ");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ENTER B : ");

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton2.setText("PLOT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout linearLayout = new javax.swing.GroupLayout(linear);
        linear.setLayout(linearLayout);
        linearLayout.setHorizontalGroup(
            linearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(linearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(linearLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(linearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(linearLayout.createSequentialGroup()
                                .addGroup(linearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(linearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        linearLayout.setVerticalGroup(
            linearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(linearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(linearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLayeredPane1.add(linear, "card3");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Y = aX^b");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ENTER A : ");

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ENTER B : ");

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton3.setText("PLOT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout powerLayout = new javax.swing.GroupLayout(power);
        power.setLayout(powerLayout);
        powerLayout.setHorizontalGroup(
            powerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(powerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(powerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(powerLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(powerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(powerLayout.createSequentialGroup()
                                .addGroup(powerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(powerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        powerLayout.setVerticalGroup(
            powerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(powerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(powerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(powerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLayeredPane1.add(power, "card7");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ENTER B : ");

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton4.setText("PLOT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("y = Ax^2 + Bx + C");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("ENTER A : ");

        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("ENTER C : ");

        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout quadLayout = new javax.swing.GroupLayout(quad);
        quad.setLayout(quadLayout);
        quadLayout.setHorizontalGroup(
            quadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(quadLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(quadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(quadLayout.createSequentialGroup()
                                .addGroup(quadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(quadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(quadLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quadLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(quadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        quadLayout.setVerticalGroup(
            quadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quadLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(quadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(quadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(quadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jButton4)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLayeredPane1.add(quad, "card4");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("y = A*B^x");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("ENTER A : ");

        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("ENTER B : ");

        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton5.setText("PLOT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout expLayout = new javax.swing.GroupLayout(exp);
        exp.setLayout(expLayout);
        expLayout.setHorizontalGroup(
            expLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(expLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(expLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(expLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(expLayout.createSequentialGroup()
                                .addGroup(expLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(expLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        expLayout.setVerticalGroup(
            expLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(expLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(expLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLayeredPane1.add(exp, "card5");

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("y = A * ln(x) + B");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("ENTER A : ");

        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("ENTER B : ");

        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton6.setText("PLOT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logLayout = new javax.swing.GroupLayout(log);
        log.setLayout(logLayout);
        logLayout.setHorizontalGroup(
            logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(logLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(logLayout.createSequentialGroup()
                                .addGroup(logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        logLayout.setVerticalGroup(
            logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLayeredPane1.add(log, "card6");

        jButton7.setText("PLOT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("y = A sin(x)");

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("ENTER A : ");

        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout sineLayout = new javax.swing.GroupLayout(sine);
        sine.setLayout(sineLayout);
        sineLayout.setHorizontalGroup(
            sineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sineLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(sineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sineLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        sineLayout.setVerticalGroup(
            sineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(sineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButton7)
                .addGap(16, 16, 16))
        );

        jLayeredPane1.add(sine, "card8");

        jButton8.setText("PLOT");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("y = A cos(x)");

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("ENTER A : ");

        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout cosineLayout = new javax.swing.GroupLayout(cosine);
        cosine.setLayout(cosineLayout);
        cosineLayout.setHorizontalGroup(
            cosineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cosineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cosineLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(cosineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cosineLayout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        cosineLayout.setVerticalGroup(
            cosineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cosineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(cosineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButton8)
                .addGap(16, 16, 16))
        );

        jLayeredPane1.add(cosine, "card9");

        jPanel2.setBackground(new java.awt.Color(204, 0, 204));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("GRAPH PLOTTING");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "linear equation", "power graph", "quadratic function", "exponential function", "logaritmic function", "sinusoidal function", "cosine function" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton9.setText("BACK");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, 0, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>                        

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        
        
    }                                          

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String box = (String)jComboBox1.getSelectedItem();
        
         if(box.equalsIgnoreCase("SELECT"))
        {
            jLayeredPane1.removeAll();
            jLayeredPane1.add(front);
            jLayeredPane1.repaint();
            jLayeredPane1.revalidate();
        }
                
        else if(box.equalsIgnoreCase("linear equation"))
        {
            jLayeredPane1.removeAll();
            jLayeredPane1.add(linear);
            jLayeredPane1.repaint();
            jLayeredPane1.revalidate();
        }
        
        else if(box.equalsIgnoreCase("power graph"))
        {
            jLayeredPane1.removeAll();
            jLayeredPane1.add(power);
            jLayeredPane1.repaint();
            jLayeredPane1.revalidate();
        }
        
        else if(box.equalsIgnoreCase("quadratic function"))
        {
            jLayeredPane1.removeAll();
            jLayeredPane1.add(quad);
            jLayeredPane1.repaint();
            jLayeredPane1.revalidate();
        }
        
        else if(box.equalsIgnoreCase("exponential function"))
        {
            jLayeredPane1.removeAll();
            jLayeredPane1.add(exp);
            jLayeredPane1.repaint();
            jLayeredPane1.revalidate();
        }
        
        else if(box.equalsIgnoreCase("logaritmic function"))
        {
            jLayeredPane1.removeAll();
            jLayeredPane1.add(log);
            jLayeredPane1.repaint();
            jLayeredPane1.revalidate();
        }
        
        else if(box.equalsIgnoreCase("sinusoidal function"))
        {
            jLayeredPane1.removeAll();
            jLayeredPane1.add(sine);
            jLayeredPane1.repaint();
            jLayeredPane1.revalidate();
        }
        
        else if(box.equalsIgnoreCase("cosine function"))
        {
            jLayeredPane1.removeAll();
            jLayeredPane1.add(cosine);
            jLayeredPane1.repaint();
            jLayeredPane1.revalidate();
        }
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int y =0;
        int x = 0;
        int counter = -25;
        String[][] graph = new String[52][52];       
        
         //-----------content------
        for(int row = 1 ; row < 51 ; row++)
        {
            for(int column = 1 ; column < 51 ; column++)
            {
                graph[row][column] = " ";
            }
            
        }
        
        //-------------border---------------
        for(int border = 0 ; border < 51 ; border++)
        {
            graph[border][0] = "/";
            graph[border][50] = "/";
            graph[0][border] = "/";
            graph[50][border] = "/";
        }
        
       
        
        //---------x&y-axis---------------




        for(int axis = 0 ; axis < 51 ; axis++)
        {
            graph[25][axis] = "/";
            graph[axis][25] = "|";
            graph[25][25] = "+"; 
        }
        
        //------------CALCULATION-------------
        
        while(counter < 100)
                {
                   
                    //calculate y 
                    int m = Integer.parseInt(jTextField1.getText());
                    int b = Integer.parseInt(jTextField2.getText());
                    
                    y = m * counter + b;
                    x = counter;
                    counter++;
                    
                    //System.out.println(y + " "+ x);
                    if(y >= 0)
                        y = 25 - y;
                    else if(y < 0)
                        y = 25 - y;
                    
                    if(x >= 0)
                        x = 25 + x;
                    else if(x < 0)
                        x = 25 + x;
                    
                    if(y > 51 || x > 51 || y < 0 || x < 0)
                        continue;
                    
                    graph[y][x] = "*";
                }
        
        showgraph a = new showgraph();
        a.setVisible(true);
        a.showdata(graph);
        
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int y =0;
        int x = 0;
        int counter = -25;
        String[][] graph = new String[52][52];       
        
         //-----------content------
        for(int row = 1 ; row < 51 ; row++)
        {
            for(int column = 1 ; column < 51 ; column++)
            {
                graph[row][column] = " ";
            }
            
        }
        
        //-------------border---------------
        for(int border = 0 ; border < 51 ; border++)
        {
            graph[border][0] = "/";
            graph[border][50] = "/";
            graph[0][border] = "/";
            graph[50][border] = "/";
        }
        
       
        
        //---------x&y-axis---------------




        for(int axis = 0 ; axis < 51 ; axis++)
        {
            graph[25][axis] = "/";
            graph[axis][25] = "|";
            graph[25][25] = "+"; 
        }
        
        //---------------------calculation------------
        while(counter < 100)
                {
                   
                    //calculate y 
                    int m = Integer.parseInt(jTextField3.getText());
                    int b = Integer.parseInt(jTextField4.getText());
                    
                    y = (int)(m * Math.pow(counter, b));
                    x = counter;
                    counter++;
                    
                    System.out.println(y + " "+ x);
                    if(y >= 0)
                        y = 25 - y;
                    else if(y < 0)
                        y = 25 - y;
                    
                    if(x >= 0)
                        x = 25 + x;
                    else if(x < 0)
                        x = 25 + x;
                    
                    if(y > 51 || x > 51 || y < 0 || x < 0)
                        continue;
                    
                    graph[y][x] = "*";
                     
                    
            }
        showgraph z = new showgraph();
        z.setVisible(true);
        z.showdata(graph);
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int y =0;
        int x = 0;
        int counter = -25;
        String[][] graph = new String[52][52];       
        
         //-----------content------
        for(int row = 1 ; row < 51 ; row++)
        {
            for(int column = 1 ; column < 51 ; column++)
            {
                graph[row][column] = " ";
            }
            
        }
        
        //-------------border---------------
        for(int border = 0 ; border < 51 ; border++)
        {
            graph[border][0] = "/";
            graph[border][50] = "/";
            graph[0][border] = "/";
            graph[50][border] = "/";
        }
        
       
        
        //---------x&y-axis---------------




        for(int axis = 0 ; axis < 51 ; axis++)
        {
            graph[25][axis] = "/";
            graph[axis][25] = "|";
            graph[25][25] = "+"; 
        }
        
        //---------------------calculation------------
        
        while(counter < 100)
                {
                   
                    //calculate y 
                    int m = Integer.parseInt(jTextField6.getText());
                    int b = Integer.parseInt(jTextField5.getText());
                    int c = Integer.parseInt(jTextField7.getText());
                    
                    y = (int)(m*Math.pow(counter, 2) + b * counter + c);
                    x = counter;
                    counter++;
                    
                    System.out.println(y + " "+ x);
                    if(y >= 0)
                        y = 25 - y;
                    else if(y < 0)
                        y = 25 - y;
                    
                    if(x >= 0)
                        x = 25 + x;
                    else if(x < 0)
                        x = 25 + x;
                    
                    if(y > 51 || x > 51 || y < 0 || x < 0)
                        continue;
                    
                    graph[y][x] = "*";
                     
                    
            }
        showgraph z = new showgraph();
        z.setVisible(true);
        z.showdata(graph);
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int y =0;
        int x = 0;
        int counter = -25;
        String[][] graph = new String[52][52];       
        
         //-----------content------
        for(int row = 1 ; row < 51 ; row++)
        {
            for(int column = 1 ; column < 51 ; column++)
            {
                graph[row][column] = " ";
            }
            
        }
        
        //-------------border---------------
        for(int border = 0 ; border < 51 ; border++)
        {
            graph[border][0] = "/";
            graph[border][50] = "/";
            graph[0][border] = "/";
            graph[50][border] = "/";
        }
        
       
        
        //---------x&y-axis---------------




        for(int axis = 0 ; axis < 51 ; axis++)
        {
            graph[25][axis] = "/";
            graph[axis][25] = "|";
            graph[25][25] = "+"; 
        }
        
        //---------------------calculation------------
        
        while(counter < 100)
                {
                   
                    //calculate y 
                    
                    int m = Integer.parseInt(jTextField8.getText());
                    int b = Integer.parseInt(jTextField9.getText());
                    
                    y =(int)( m * Math.pow(b, counter));
                    x = counter;
                    counter++;
                    
                    System.out.println(y + " "+ x);
                    if(y >= 0)
                        y = 25 - y;
                    else if(y < 0)
                        y = 25 - y;
                    
                    if(x >= 0)
                        x = 25 + x;
                    else if(x < 0)
                        x = 25 + x;
                    
                    if(y > 51 || x > 51 || y < 0 || x < 0)
                        continue;
                    
                    graph[y][x] = "*";
                     
                    
                    
                }
        showgraph z = new showgraph();
        z.setVisible(true);
        z.showdata(graph);
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int y =0;
        int x = 0;
        int counter = -25;
        String[][] graph = new String[52][52];       
        
         //-----------content------
        for(int row = 1 ; row < 51 ; row++)
        {
            for(int column = 1 ; column < 51 ; column++)
            {
                graph[row][column] = " ";
            }
            
        }
        
        //-------------border---------------
        for(int border = 0 ; border < 51 ; border++)
        {
            graph[border][0] = "/";
            graph[border][50] = "/";
            graph[0][border] = "/";
            graph[50][border] = "/";
        }
        
       
        
        //---------x&y-axis---------------




        for(int axis = 0 ; axis < 51 ; axis++)
        {
            graph[25][axis] = "/";
            graph[axis][25] = "|";
            graph[25][25] = "+"; 
        }
        
        //---------------------calculation------------
        
        while(counter < 100)
                {
                   
                    //calculate y 
                    
                    int m = Integer.parseInt(jTextField10.getText());
                    int b = Integer.parseInt(jTextField11.getText());
                    
                    y = (int)(m  * Math.log(x) + b);
                    x = counter;
                    counter++;
                    
                    System.out.println(y + " "+ x);
                    if(y >= 0)
                        y = 25 - y;
                    else if(y < 0)
                        y = 25 - y;
                    
                    if(x >= 0)
                        x = 25 + x;
                    else if(x < 0)
                        x = 25 + x;
                    
                    if(y > 51 || x > 51 || y < 0 || x < 0)
                        continue;
                    
                    graph[y][x] = "*";
                     
                    
                    
                }
         showgraph z = new showgraph();
        z.setVisible(true);
        z.showdata(graph);
    }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int y =0;
        int x = 0;
        int counter = -25;
        String[][] graph = new String[52][52];       
        
         //-----------content------
        for(int row = 1 ; row < 51 ; row++)
        {
            for(int column = 1 ; column < 51 ; column++)
            {
                graph[row][column] = " ";
            }
            
        }
        
        //-------------border---------------
        for(int border = 0 ; border < 51 ; border++)
        {
            graph[border][0] = "/";
            graph[border][50] = "/";
            graph[0][border] = "/";
            graph[50][border] = "/";
        }
        
       
        
        //---------x&y-axis---------------




        for(int axis = 0 ; axis < 51 ; axis++)
        {
            graph[25][axis] = "/";
            graph[axis][25] = "|";
            graph[25][25] = "+"; 
        }
        
        //---------------------calculation------------
        
        while(counter < 100)
                {
                   
                    //calculate y 
                    int m = Integer.parseInt(jTextField12.getText());
                    double rad = (counter + Math.PI * 180);
                    y = (int)(m * Math.sin(rad));
                    x = counter;
                    counter++;
                    
                    System.out.println(y + " "+ x);
                    if(y >= 0)
                        y = 25 - y;
                    else if(y < 0)
                        y = 25 - y;
                    
                    if(x >= 0)
                        x = 25 + x;
                    else if(x < 0)
                        x = 25 + x;
                    
                    if(y > 51 || x > 51 || y < 0 || x < 0)
                        continue;
                    
                    graph[y][x] = "*";    
                }
        
         showgraph z = new showgraph();
        z.setVisible(true);
        z.showdata(graph);
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int y =0;
        int x = 0;
        int counter = -25;
        String[][] graph = new String[52][52];       
        
         //-----------content------
        for(int row = 1 ; row < 51 ; row++)
        {
            for(int column = 1 ; column < 51 ; column++)
            {
                graph[row][column] = " ";
            }
            
        }
        
        //-------------border---------------
        for(int border = 0 ; border < 51 ; border++)
        {
            graph[border][0] = "/";
            graph[border][50] = "/";
            graph[0][border] = "/";
            graph[50][border] = "/";
        }
        
       
        
        //---------x&y-axis---------------




        for(int axis = 0 ; axis < 51 ; axis++)
        {
            graph[25][axis] = "/";
            graph[axis][25] = "|";
            graph[25][25] = "+"; 
        }
        
        //---------------------calculation------------
        
        while(counter < 100)
                {
                   
                    //calculate y 
                    int m = Integer.parseInt(jTextField13.getText());
                    double rad = (counter + Math.PI * 180);
                    y = (int)(m * Math.cos(rad));
                    x = counter;
                    counter++;
                    
                    System.out.println(y + " "+ x);
                    if(y >= 0)
                        y = 25 - y;
                    else if(y < 0)
                        y = 25 - y;
                    
                    if(x >= 0)
                        x = 25 + x;
                    else if(x < 0)
                        x = 25 + x;
                    
                    if(y > 51 || x > 51 || y < 0 || x < 0)
                        continue;
                    
                    graph[y][x] = "*";
                     
                    
                    
                }
        
        showgraph z = new showgraph();
        z.setVisible(true);
        z.showdata(graph);
    }                                        

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        dispose();
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(graphplot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(graphplot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(graphplot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(graphplot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new graphplot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel cosine;
    private javax.swing.JPanel exp;
    private javax.swing.JPanel front;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel linear;
    private javax.swing.JPanel log;
    private javax.swing.JPanel power;
    private javax.swing.JPanel quad;
    private javax.swing.JPanel sine;
    // End of variables declaration                   
}
